### PR TITLE
Add missing "1 month" option

### PR DESCRIPTION
**Pull request by RudeySH**
Last.fm supports period=1month, so I'm adding it.

### CODE REVIEW

**Comment by Dinduks** [comment]
Merged and deployed.

Didn't even know people still use that.  
What do you use it for?

**Comment by RudeySH** [comment]
I was trying out every single collage generator I could find. Yours is one the best ones out there, it's the only one that can generate up to 20x20 collages AND has configurable image sizes.

**Comment by Dinduks** [comment]
What do you use the collages for?

**Comment by RudeySH** [comment]
Mostly for sharing them on https://www.reddit.com/r/lastfm/ and the [Last.fm Discord](https://www.reddit.com/r/lastfm/comments/g430ov/come_and_join_us_on_lastfm_discord_its_a_fun/).

**Pull request merged**
